### ISSUE TITLE
怎么操作

### ISSUE THREAD

**Issue by kangleblue** [yhforthefreedom/iOSToolBox#1]
我执行 pip3 install -U tidevice 命令 完了之后，怎么 才能 打开 你那界面呢https://github.com/yhforthefreedom/iOSToolBox/blob/master/iOSToolBox.png

**Comment by yhforthefreedom** [comment]
1.我上传项目的dist文件夹有exe包，不过好像不是最新版本的
2把项目拉下来在项目根目录敲命令pyinstaller -F ios_toolbox.py进行打包，打包成功就是一个exe可执行文件

**Comment by kangleblue** [comment]
我进入到 dist目录，点击 生成好的exe文件，窗口闪一下 就自动关闭了  @yhforthefreedom 啥原因呢，pyinstaller -F ios_toolbox.py 编译都是成功的
25241 INFO: Copying 0 resources to EXE
25242 INFO: Emedding manifest in EXE
25244 INFO: Updating manifest in D:\iOSToolBox-master\dist\ios_toolbox.exe.notanexecutable
25302 INFO: Updating resource type 24 name 1 language 0
25304 INFO: Appending PKG archive to EXE
28004 INFO: Building EXE from EXE-00.toc completed successfully.

**Comment by kangleblue** [comment]
@yhforthefreedom

**Comment by yhforthefreedom** [comment]
你使用的是windows电脑吗，命令行窗口是跟着程序绑定在一起的，按理说不可能一下子自动关系，有报错信息吗

**Comment by kangleblue** [comment]
windows10 系统，没有任何报错信息，wx kangleblue ，qq 280803858
